### ISSUE TITLE
未说明页面添加代码

### ISSUE THREAD

**Issue by MualaniMarine** [Instrye/typecho_GoogleRecaptcha#2]

**Comment by nyufeng** [comment]
不是很懂你的意思。

**Comment by MualaniMarine** [comment]
像同类插件 会有在页面内插入一段代码 比如`<?php reCAPTCHA_Plugin::output(); ?>`  。 但你的项目内并未说明，是否是不需要添加

**Comment by nyufeng** [comment]
不需要修改任何页面内容 开启插件会通过接口自动注入到登录页面
